blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'

urlpatterns = [
    #Auth
    path('blog/register',views.register,name="user_register"),
    path('blog/login',views.ingreso,name="user_login"),
    path('blog/logout',views.salir,name="user_logout"),
    #Blog
    path('blog/',views.post_list,name="post_list"),
    path('blog/add',views.post_add,name="post_add"),
    path('blog/<slug:post>/',views.post_detail,name="post_detail"),
    path('blog/tag/<slug:tag_slug>/',views.post_list, name='post_list_by_tag'),
]

server/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('blog.urls','blog'))),
]

blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
from taggit.managers import TaggableManager



class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,self).get_queryset().filter(status='publicado')

class Post(models.Model):

    STATUS_CHOICES = (
        ('borrador', 'Borrador'),
        ('publicado', 'Publicado'),
    )

    objects = models.Manager()
    published = PublishedManager()    
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE,related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,choices=STATUS_CHOICES,default='borrador')
    tags = TaggableManager()


    class Meta:
        ordering = ('-publish',)

    def __str__(self) -> str:
        return self.title


    def get_absolute_url(self):
        return reverse("blog:post_detail", args=[
            self.slug
        ])
    

class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f"Comment by {self.name} on {self.post}"

blog/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Comment, Post
from django.contrib.auth.models import User, Group, Permission


class RegisterForm(forms.ModelForm):
    grupo = forms.MultipleChoiceField(
        choices=((choice.id, choice.name) for choice in Group.objects.all()),
        label="Grupos",
        required=False
    )
    permisos = forms.MultipleChoiceField(
        choices=((choice.id, choice.name)
                 for choice in Permission.objects.all()),
        label="Permisos",
        required=False
    )
    password2 = forms.PasswordInput()

    def clean_password2(self):
        password = self.cleaned_data['password']
        password2 = self.cleaned_data['password2']

        if(password != password2):
            raise ValidationError('Las contraseñas no coinciden.')
        return password2

    class Meta:
        model = User
        fields = ("username", "email", "password")




class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput,
        required=True,
        min_length=6,
        )
    password = forms.CharField(
        widget=forms.PasswordInput,
        min_length=6,
        required=True,
        )

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'slug','body')

blog/views.py
from django.shortcuts import render, get_object_or_404,redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from .models import Post
from .forms import CommentForm, PostForm, LoginForm, RegisterForm
from taggit.models import Tag
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.models import Group,User
from django.contrib.auth.decorators import login_required,permission_required


def ingreso(request):

    form = LoginForm(request.POST or None)
    mensaje = None
    if form.is_valid():
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('blog:post_list')
        else:
            mensaje = "Login incorrecto"

    context = {'form': form, 'mensaje': mensaje}

    return render(request, 'blog/login.html', context)


def register(request):
    form = RegisterForm(request.POST or None)
    grupos = Group.objects.all()
    mensaje = None
    if form.is_valid():
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        grupo = form.cleaned_data['grupo']
        
        user = User.objects.create(username= username)
        user.set_password(password)            
        user.save()
        user.groups.set(grupo)
        return redirect('blog:user_login')
    
    context = {'form':form,'mensaje':mensaje,"grupos":grupos}
    return render(request,'blog/register.html',context)  


def salir(request):
    logout(request)
    return redirect('blog:user_login')


@permission_required('blog.add_post', login_url='blog:user_login')
def post_add(request):
    form = PostForm(request.POST or None)
    if form.is_valid():
        form.save()
    context = {
       "form":form
    }
    return render(request, 'blog/post/add.html', context)


def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    page = request.GET.get('page')
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 5)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {
        'posts': posts
    }
    return render(request, 'blog/post/list.html', context)


def post_detail(request, post):
    post = get_object_or_404(Post, slug=post, status='publicado')
    comments = post.comments.filter(active=True)

    new_comment = None
    comment_form = CommentForm(request.POST or None)

    if(request.method == 'POST'):
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()

    context = {
        'post': post,
        'comments': comments,
        'comment_form': comment_form,
        'new_comment': new_comment
    }
    return render(request,'blog/post/detail.html', context)

blog/templates/blog/base.html
{% load crispy_forms_tags %}   
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.80.0">
    <title>{% block title %} Blog {% endblock %} </title>

    

    <!-- Bootstrap core CSS -->
<link href="{% static 'blog/css/bootstrap.min.css' %}" rel="stylesheet">



    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/4.6/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/4.6/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/4.6/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/4.6/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/4.6/assets/img/favicons/safari-pinned-tab.svg" color="#563d7c">
<link rel="icon" href="/docs/4.6/assets/img/favicons/favicon.ico">
<meta name="msapplication-config" content="/docs/4.6/assets/img/favicons/browserconfig.xml">
<meta name="theme-color" content="#563d7c">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="https://fonts.googleapis.com/css?family=Playfair&#43;Display:700,900" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'blog/css/blog.css' %}" rel="stylesheet">
  </head>
  <body>
    
<div class="container">
  <header class="blog-header py-3">
    <div class="row flex-nowrap justify-content-between align-items-center">
      <div class="col-4 pt-1">
      {% if perms.blog.add_post %}
        <a class="text-muted" href="{% url 'blog:post_add' %}">Publicar</a>
        {% endif %}
      </div>
      <div class="col-4 text-center">
        <a class="blog-header-logo text-dark" href="#">Django Blog</a>
      </div>
      <div class="col-4 d-flex justify-content-end align-items-center">
        <a class="text-muted" href="#" aria-label="Search">
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="mx-3" role="img" viewBox="0 0 24 24" focusable="false"><title>Search</title><circle cx="10.5" cy="10.5" r="7.5"/><path d="M21 21l-5.2-5.2"/></svg>
        </a>
        {% if not request.user.is_authenticated %} 
        <a class="btn btn-sm btn-outline-secondary" href="{% url 'blog:user_login' %}">Ingreso</a>
        &nbsp
        <a class="btn btn-sm btn-outline-secondary" href="{% url 'blog:user_register' %}">Registro</a>
        {% else %}
        &nbsp
        {{ request.user }}
        <a class="btn btn-sm btn-outline-secondary" href="{% url 'blog:user_logout' %}">Salir</a>
        {% endif %}
      </div>
    </div>
  </header>

  


  
</div>

<main role="main" class="container">
  {% block content %}
  {% endblock %}
     


</main><!-- /.container -->

<footer class="blog-footer">
  <p>Blog template built for <a href="https://getbootstrap.com/">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>


    
  </body>
</html>

blog/templates/blog/index.html
{% extends './base.html' %}
{% block title %} Inicio {% endblock %}


{% block content %}

{% endblock %}

blog/templates/blog/login.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-12 col-md-6 offset-md-3 mb-5">
            <form action="{% url 'blog:user_login' %}" method="POST">
            <h2 class="mt-4">Ingreso</h2>
            {% csrf_token %}
            {{ form | crispy }}            
            {% if mensaje is not None %}
            <div class="alert alert-danger" role="alert">
                {{ mensaje }}
            </div>
            {% endif %}            
            <input type="submit" value="Ingresar" class="btn btn-primary">
        </form>
        </div>
    </div>    
</div>
{% endblock %}

blog/templates/blog/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>

        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">next</a>
            <a href="?page={{ page.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

blog/templates/blog/post/add.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block title %}My Blog{% endblock %}

{% block content %}
<h1>Nueva publicacion</h1>
<form action="{% url 'blog:post_add'%}" method="POST">
    {% csrf_token %}
    {{ form | crispy }}  
    <input type="submit" value="Publicar">
</form>

{% include "blog/pagination.html" with page=page_obj %}
{% endblock%}

blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}
{% block title %}Django Blog{% endblock %}

{% block content %}

<p class="date">
    Publicado {{ post.publish }} por {{ post.author }}
</p>
{{ post.body }}

<p class="tags">
    Etiquetas:
    {% for tag in post.tags.all %}
    <a href="{% url "blog:post_list_by_tag" tag.slug %}">
    {{ tag.name }}
    </a>
    {% endfor %}
    </p>
    
{% with comments.count as total_comments %}
<h2>
    {{ total_comments }} comentario{{ total_comments|pluralize }}
</h2>
{% endwith %}
{% for comment in comments %}
<div class="comment">
<p class="info">
Comentario {{ forloop.counter }} por {{ comment.name }}
{{ comment.created }}
</p>
{{ comment.body }}
</div>
{% empty %}
<p>Sin Comentarios.</p>
{% endfor %}

{% if new_comment %}
<h2>Tu comentario ha sido agregado.</h2>
{% else %}
<h2>Añadir un nuevo comentario</h2>
<form method="post">
    {{ comment_form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Add comment"></p>
</form>
{% endif %}

<hr>



{% endblock%}

blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}
{% block title %}My Blog{% endblock %}

{% block content %}
<h1>My Blog</h1>
{% for post in posts %}
<h2>
<a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
</h2>
<p class="date">
    Published {{ post.publish }} by {{ post.author }}
</p>
<p class="tags">
Tags:
{% for tag in post.tags.all %}
<a href="{% url "blog:post_list_by_tag" tag.slug %}">
{{ tag.name }}
</a>
{% if not forloop.last %}, {% endif %}
{% endfor %}
</p>

{{ post.body |truncatewords:30|linebreaks }}

{% endfor %}
{% include "blog/pagination.html" with page=page_obj %}
{% endblock%}

blog/templates/blog/register.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-12 col-md-6 offset-md-3">
            <form action="{% url 'blog:user_register' %}" method="POST">
            <h2 class="mt-4">Registro</h2>
            {% csrf_token %}
            {{ form | crispy }}            
            {% if mensaje is not None %}
            <div class="alert alert-danger" role="alert">
                {{ mensaje }}
            </div>
            {% endif %}            
            <input type="submit" value="Registrar" class="btn btn-primary">
        </form>
        </div>
    </div>
    
</div>
{% endblock %}